### ISSUE TITLE
2.3 version install broken?

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#19]
_I am really excited to see that you have come back to the development of `samewords`!_ 

First thing I tried was to install the released version through the easy installation. The `pip3 install samewords` runs through w/o errors and `samewords --help` reacts correctly.

But `pytest` gives:

```python
====================================================================== ERRORS =======================================================================
________________________________________________________ ERROR collecting test/test_core.py _________________________________________________________
test/test_core.py:6: in <module>
    class TestMainProcessing:
test/test_core.py:9: in TestMainProcessing
    './samewords/test/assets/da-49-l1q1-processed.tex')
document.py:21: in doc_content
    with open(filename, mode='r', encoding='utf-8') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: './samewords/test/assets/da-49-l1q1-processed.tex'
______________________________________________________ ERROR collecting test/test_document.py _______________________________________________________
test/test_document.py:9: in <module>
    multi_begins = doc_content('./samewords/test/assets/multi_begins.tex')
document.py:21: in doc_content
    with open(filename, mode='r', encoding='utf-8') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: './samewords/test/assets/multi_begins.tex'
_________________________________________________ ERROR collecting test/test_document_processing.py _________________________________________________
test/test_document_processing.py:10: in <module>
    class TestParagraphHandling:
test/test_document_processing.py:11: in TestParagraphHandling
    document = doc_content('./samewords/test/assets/da-49-l1q1.tex')
document.py:21: in doc_content
    with open(filename, mode='r', encoding='utf-8') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: './samewords/test/assets/da-49-l1q1.tex'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

``` 

Trying to run it on a testfile (eg from #15) nonetheless gives:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/samewords/tokenize.py", line 408, in _tokenize
    open_idx = self._stack_bracket[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/samewords/cli.py", line 79, in main
    print(samewords.core.process_document(filename))
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 26, in process_document
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 26, in <listcomp>
    chunk = ''.join([run_annotation(par) for par in chunk_pars(chunk)])
  File "/usr/local/lib/python3.6/site-packages/samewords/core.py", line 10, in run_annotation
    tokenization = Tokenizer(input_text)
  File "/usr/local/lib/python3.6/site-packages/samewords/tokenize.py", line 283, in __init__
    self.wordlist = self._wordlist()
  File "/usr/local/lib/python3.6/site-packages/samewords/tokenize.py", line 293, in _wordlist
    word, pos = self._tokenize(self.data, pos)
  File "/usr/local/lib/python3.6/site-packages/samewords/tokenize.py", line 415, in _tokenize
    word.close_macro(0)
  File "/usr/local/lib/python3.6/site-packages/samewords/tokenize.py", line 166, in close_macro
    raise IndexError('The word does not have any open macros.')
IndexError: The word does not have any open macros.
```

If I download `2.0` or `2.3` zips here from GitHub, the `pytest` is passed (!) but the errors for a real file are the same as with the `pip`-version with small variance (file-paths and linenumbers).

I am using MacOS 10.12.6 with homebrew Python 3.6.4.

**Comment by stenskjaer** [comment]
Great to hear! 

Thank you for the report. I think the problem with the missing files should be relatively simple, so I'll look at it tonight (Canadian time, so you'll probably not see anything until tomorrow). 

I don't know about the other one. We'll see when I dig into it. I'm planning to work more on this in the weekend so hopefully there should be some more progress soon.

Cheers!

**Comment by stenskjaer** [comment]
Okay. Actually we have two issues here.

About the tests: After several more or less successful attempts I actually got the test thing to work on the pypi package too. But then I realised that actually I don't think it is part of the idea of the bdist distribution (which is what you install with `pip install ...`) that you run tests on that. So now you get the test assets included if you download the source distribution, either from pypi or Github, but not if you run the `pip install` and navigate to the source files somewhere in your python `site-packages` directory. 

About the other problem: That was a stupid bug which I hope is solved now in branch [issue-19](https://github.com/stenskjaer/samewords/tree/issue-19). Maybe you could confirm that it works with a test file (where a macro is followed by a linebreak without any intervening whitespace, such as the one in issue 15, this was the case that the bug did not handle correctly)?

**Comment by floriandk** [comment]
Wow, that's what I call a swift fix!

> About the tests: After several more or less successful attempts I actually got the test thing to work on the pypi package too. But then I realised that actually I don't think it is part of the idea of the bdist distribution (which is what you install with pip install ...) that you run tests on that. So now you get the test assets included if you download the source distribution, either from pypi or Github, but not if you run the pip install and navigate to the source files somewhere in your python site-packages directory.

Looking closely at the readme actually shows that "Remember the tests" is a subsection under "For development" so I could have figured out that this isn't needed for the "Easy installation"...

Anyway it is still not quite clear to me whether I should be testing the install from the zips of the branches. Fwiw the `pytest` on "issue-19"-branch gives:

```python
___________________________________________________ ERROR collecting samewords/test/test_core.py ____________________________________________________
test/test_core.py:6: in <module>
    class TestMainProcessing:
test/test_core.py:9: in TestMainProcessing
    './samewords/test/assets/da-49-l1q1-processed.tex')
document.py:21: in doc_content
    with open(filename, mode='r', encoding='utf-8') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: './samewords/test/assets/da-49-l1q1-processed.tex'
_________________________________________________ ERROR collecting samewords/test/test_document.py __________________________________________________
test/test_document.py:9: in <module>
    multi_begins = doc_content('./samewords/test/assets/multi_begins.tex')
document.py:21: in doc_content
    with open(filename, mode='r', encoding='utf-8') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: './samewords/test/assets/multi_begins.tex'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

> About the other problem: That was a stupid bug which I hope is solved now in branch issue-19. Maybe you could confirm that it works with a test file (where a macro is followed by a linebreak without any intervening whitespace, such as the one in issue 15, this was the case that the bug did not handle correctly)?

On the bright side the installed `samewords` 0.2.7 works on some simple test files, e.g. the one from #15 👍 
I'll be running some more detailed tests on different files in the course of the day.

EDIT: I have not pushed the latest update to pypi because I want to wait until I'm sure this bug is fixed too.

**Comment by stenskjaer** [comment]
Ahh now I see the confusion with the tests. It is not the idea that you need to run any of the automated tests when you are asked to test a branch. They are used when I develop to make sure things work as expected after and during changes. Often bug reports get incorporated into the tests (for example your testing examples can easily end up in the automated tests in some version), so when I ask you to confirm that something works that should already work in one of the tests. 

But I also want it confirmed that it also works on your environment and not only in the test suite.

Anyway. I have added a bit of clarification about the automated tests to the README.

Another thing: I don't understand why `pytest` doesn't work for you on a zip of the `issue-19` branch. If I download that, unzip it and simply navigate to that directory and run `pytest` they all pass... Hmmm...
