### ISSUE TITLE
Linebreaks and tabs

### ISSUE THREAD

**Issue by floriandk** [stenskjaer/samewords#6]
On MacOS 10.12 linebreaks are not treated correctly.

A UTF8-file saved with Unix LF produces a LaTeX-file that will compile but `\sameword` is applied incorrectly at the linebreak:

```latex
Leo aut ursus aut oryx aut ricinus aut equus aut
lupus \edtext{aut}{\Afootnote{et}\Bfootnote{monotone\ldots}} canis aut felix aut asinus \edtext{aut}{\Bfootnote{et}} burricus.
```

becomes    

```latex
Leo \sameword{aut} ursus \sameword{aut} oryx \sameword{aut} ricinus \sameword{aut} equus \sameword{aut
lupus} \edtext{\sameword[1]{aut}}{\Afootnote{et}\Bfootnote{monotone\ldots}} canis \sameword{aut} felix \sameword{aut} asinus \edtext{\sameword{aut}}{\Bfootnote{et}} burricus.
```

A similar problem occurs with tabs (shown here with `<tab/>`) in the source file:

```latex
Leo  aut ursus aut  oryx<tab/>aut ricinus aut<tab/>equus <tab/>aut lupus aut<tab/> canis aut felix aut asinus \edtext{aut}{\Bfootnote{et}} burricus.
```

becomes

```latex
Leo  \sameword{aut} ursus \sameword{aut}  \sameword{oryx<tab/>aut} ricinus \sameword{aut<tab/>equus} \sameword{<tab/>aut} lupus \sameword{aut<tab/>} canis \sameword{aut} felix \sameword{aut} asinus \edtext{\sameword[1]{aut}}{\Bfootnote{et}} burricus.
```

As LaTeX normalizes tabs and linebreaks to whitespace, I suppose `samewords` could, too, couldn't it?

I am aware that I could do some preprocessing. But I use linebreaks and tabs heavily to keep the `reledmac`-code human-readable, especially when I have to deal with many variants. So a built-in solution would be really appreciated.

For completeness sake: When saved with Win CRLF or Mac CR linebreaks the same problem occurs at the linebreak, but also the preamble is garbled to only:

```latex
 \documentclass[\pstart
```

I don't care much for which linebreak format I have to use, but it would be really good if one of them would work.

**Comment by floriandk** [comment]
This obviously also affects cases when the first word in a paragraph has to be marked with `\sameword`, e.g. 

```latex
et cetera \edtext{et}{\Afootnote{÷}} cetera et cetera
```

becomes

```latex
et} cetera \edtext{\sameword[1]{et}}{\Afootnote{÷}} cetera \sameword{et} cetera
```

**Comment by stenskjaer** [comment]
Thanks a lot for this and your other great bug reports.

I'm on vacation now but will be back Saturday and will look at it after
then.

**Comment by floriandk** [comment]
Perfect! Next week I will be away from the computer, though, in case you want me to test more.
I really appreciate your dedicated work on this!

**Comment by stenskjaer** [comment]
You can test the main part of this bug in the branch [issue-6](https://github.com/stenskjaer/samewords/tree/issue-6). I will create a new issue for the problem about the Win CRLF or Mac CR linebreaks.

**Comment by stenskjaer** [comment]
@floriandk would you mind testing the linebreaks problems in [issue-9](https://github.com/stenskjaer/samewords/tree/issue-9) and report back in issue #9?

By the way, I have introduced a new bug with the current changes which means that if `docopt` is not installed when you try installing the test branches, it will throw an error. I can't really correct that before we have merged these branches, though. So when testing, you will have to install docopt manually before running `pip install -e .` in the virtual env from the branch directory.

**Comment by stenskjaer** [comment]
@floriandk I wonder if you have a chance to test these changes. I'm think they are solved, but I'll hold of merging them in until the end of the week to let you confirm it.

Cheers!

**Comment by floriandk** [comment]
Both the MWEs and my other simplified test files are tagged correctly with the issue6-branch on my system. I'll do some more test with real life files, when I get #7 to work.

**Comment by floriandk** [comment]
I just noticed that there's still something with tabs or lb directly before the `\lemma`.
With branch issue9 (this includes the same fix as branch issue6, doesn't it?)

```latex
\documentclass{article}

\usepackage[series={A,B},nofamiliar,noeledsec,noledgroup,draft]{reledmac}


\begin{document}

\beginnumbering
\pstart
A \edtext{A \edtext{B}{\Afootnote{b}} C}{
\lemma{A \ldots{} C}\Afootnote{a b c}} C
\pend
\endnumbering

\end{document}
```

stalls with 

```python
Starting conversion.
Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    load_entry_point('samewords', 'console_scripts', 'samewords')()
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/cli.py", line 61, in main
    output_content = samewords.core.process_document(filename)
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/core.py", line 14, in process_document
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/core.py", line 14, in <listcomp>
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 781, in critical_note_match_replace_samewords
    result = sub_processing(TextSegment(text))
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 23, in __init__
    list.__init__(self, self.content_split(input_string))
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 46, in content_split
    return_list.append(CritText(search_string[appnote_start:appnote_end]))
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 70, in __init__
    self.lemma_content = self.get_lemma_content()
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 107, in get_lemma_content
    return Brackets(self.critical_note, start=len(r'\lemma')).content
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 325, in __init__
    self.content = self.content(search_string, start, macro)
  File "TeX-testing/sameword-test/samewords-issue-9/samewords/annotate.py", line 359, in content
    "Context: %s" % search_string[position:position + 50])
ValueError: The first symbol of the match string must be an opening bracket ({). 
Context: a{A \ldots{} C}\Afootnote{a b c}
```

If I replace the lb before `\lemma` with a tab, the problem persists; if I remove it, the problem disappears.

**Comment by stenskjaer** [comment]
That's right. I have pushed an update to https://github.com/stenskjaer/samewords/tree/issue-6 that you can try.

**Comment by stenskjaer** [comment]
I'll close this now, but if you feel like testing the branch, I'll keep it open there for a while yet.

**Comment by floriandk** [comment]
Thanks for your patience!

When I test branch issue6 (latest change 590e196  on 7 Aug) with the MWE as above (space or tab), I get:
```python
Traceback (most recent call last):
  File "/usr/local/bin/samewords", line 11, in <module>
    load_entry_point('samewords', 'console_scripts', 'samewords')()
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/cli.py", line 61, in main
    output_content = samewords.core.process_document(filename)
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/core.py", line 14, in process_document
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/core.py", line 14, in <listcomp>
    updated_paragraphs = [annotate.critical_note_match_replace_samewords(par) for par in paragraphs]
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/annotate.py", line 782, in critical_note_match_replace_samewords
    result = sub_processing(TextSegment(text))
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/annotate.py", line 23, in __init__
    list.__init__(self, self.content_split(input_string))
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/annotate.py", line 46, in content_split
    return_list.append(CritText(search_string[appnote_start:appnote_end]))
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/annotate.py", line 70, in __init__
    self.lemma_content = self.get_lemma_content()
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/annotate.py", line 107, in get_lemma_content
    return Brackets(self.critical_note, macro=r'\lemma').content
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/annotate.py", line 323, in __init__
    self.content = self.content(search_string, start, macro)
  File "TeX-testing/sameword-test/samewords-issue-6/samewords-issue-6/samewords/annotate.py", line 352, in content
    % (macro, position, search_string[position:position + 20]))
ValueError: The indicated macro, \lemma, did not occur at position 0.Context: 
\lemma{A \ldots{} C
```

Can you reproduce this?
